### ISSUE TITLE
Handler error: [string "scripts/manager_effect_aura.lua"]: 31: attempt to call field 'isDyingOrDead' (a nil value)

### ISSUE THREAD

**Issue by dkniffin** [FG-Unofficial-Developers-Guild/FG-Aura-Effect#18]
I've been using this extension for a while now with no issue. However, I recently discovered that I can install it via the Forge instead, so I just did that. Now I'm getting this error:

```
Handler error: [string "scripts/manager_effect_aura.lua"]: 31: attempt to call field 'isDyingOrDead' (a nil value)
```

Any idea what might be causing that?

**Comment by dkniffin** [comment]
Oh, and this error occurs when:
- I open the combat tracker
- I open the map
- I move a character token around who has an aura applied

**Comment by bmos** [comment]
The isDyingOrDead function is part of ActorHealthManager in CoreRPG. I'm pretty sure it was introduced in the lastest round of rulesets updates.

Since you got the extension on Forge you must be using Unity, so you should also have the latest ruleset updates...

Perhaps in your ruleset folder you have extracted CoreRPG's pak file to a folder at some point before these latest updates?
If you have a folder and a pak file (or a folder and an ext or a folder and a mod in each respective folder) FG uses the folder instead of the packed file. So if you extract a ruleset (for easier viewing or editing), then any updates it downloads get ignored. I'm assuming you're still using an old version of CoreRPG (and possibly others).

When you load your campaign, the announcement message of all loaded rulesets and extensions will post to chat. CoreRPG's message should be "Core RPG ruleset (2022-03-20)".

**Comment by dkniffin** [comment]
@bmos Bingo! I had both CoreRPG and 5e unpacked to inspect their contents (I was working on my own themes and extensions, and that made it easier to view). Deleting those fixed it (and got me some new updates that I didn't know I was missing haha). Thanks!

**Comment by bmos** [comment]
You're welcome!
I suggest extracting the rulesets to a separate folder somewhere (which also gives you a good point of reference when checking what has changed in a new update).
